"""change id col from string to int

Revision ID: 1b1c2a90605e
Revises: c925a7638cfb
Create Date: 2020-07-07 13:33:57.760012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b1c2a90605e'
down_revision = 'c925a7638cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_str', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('screen_name', sa.String(length=32), nullable=True))

    op.alter_column('users', 'id',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Integer(),
               autoincrement=True)
    op.create_unique_constraint(None, 'users', ['id_str'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=32),
               autoincrement=True)
    op.drop_column('users', 'screen_name')
    op.drop_column('users', 'id_str')
    # ### end Alembic commands ###
