"""user and word table

Revision ID: 710eea5df069
Revises: 
Create Date: 2020-05-20 14:15:44.958965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710eea5df069'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('english', sa.Boolean(), nullable=True),
    sa.Column('french', sa.Boolean(), nullable=True),
    sa.Column('german', sa.Boolean(), nullable=True),
    sa.Column('hindi', sa.Boolean(), nullable=True),
    sa.Column('mandarin_chinese', sa.Boolean(), nullable=True),
    sa.Column('portuguese', sa.Boolean(), nullable=True),
    sa.Column('spanish', sa.Boolean(), nullable=True),
    sa.Column('arabic', sa.Boolean(), nullable=True),
    sa.Column('dutch', sa.Boolean(), nullable=True),
    sa.Column('russian', sa.Boolean(), nullable=True),
    sa.Column('italian', sa.Boolean(), nullable=True),
    sa.Column('japanese', sa.Boolean(), nullable=True),
    sa.Column('mon', sa.Boolean(), nullable=True),
    sa.Column('tues', sa.Boolean(), nullable=True),
    sa.Column('wed', sa.Boolean(), nullable=True),
    sa.Column('thurs', sa.Boolean(), nullable=True),
    sa.Column('fri', sa.Boolean(), nullable=True),
    sa.Column('sat', sa.Boolean(), nullable=True),
    sa.Column('sun', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('word', sa.Text(), nullable=False),
    sa.Column('langauge', sa.Text(), nullable=False),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('song', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('users')
    # ### end Alembic commands ###
