"""update col name

Revision ID: c925a7638cfb
Revises: 
Create Date: 2020-06-22 14:56:07.740103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c925a7638cfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('subscribed', sa.Boolean(), nullable=True),
    sa.Column('english', sa.Boolean(), nullable=True),
    sa.Column('french', sa.Boolean(), nullable=True),
    sa.Column('german', sa.Boolean(), nullable=True),
    sa.Column('hindi', sa.Boolean(), nullable=True),
    sa.Column('mandarin_chinese_simplified', sa.Boolean(), nullable=True),
    sa.Column('portuguese', sa.Boolean(), nullable=True),
    sa.Column('spanish', sa.Boolean(), nullable=True),
    sa.Column('arabic', sa.Boolean(), nullable=True),
    sa.Column('dutch', sa.Boolean(), nullable=True),
    sa.Column('russian', sa.Boolean(), nullable=True),
    sa.Column('italian', sa.Boolean(), nullable=True),
    sa.Column('japanese', sa.Boolean(), nullable=True),
    sa.Column('mon', sa.Boolean(), nullable=True),
    sa.Column('tues', sa.Boolean(), nullable=True),
    sa.Column('wed', sa.Boolean(), nullable=True),
    sa.Column('thurs', sa.Boolean(), nullable=True),
    sa.Column('fri', sa.Boolean(), nullable=True),
    sa.Column('sat', sa.Boolean(), nullable=True),
    sa.Column('sun', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('words',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('article', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('song', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    op.drop_table('users')
    # ### end Alembic commands ###
